[global]
developmentMode = false

[server]
port = 12000
address = "0.0.0.0"
allowRunOnSave = true
runOnSave = true
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1f4e79"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"